# Generated by Django 4.2.17 on 2025-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oveja',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vendida', 'Vendida'), ('muerta', 'Muerta'), ('comprada', 'Comprada')], default='activa', max_length=10),
        ),
    ]
