# Generated by Django 4.2.17 on 2025-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0002_alter_oveja_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='oveja',
            name='comprada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oveja',
            name='en_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oveja',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vendida', 'Vendida'), ('muerta', 'Muerta')], default='activa', max_length=10),
        ),
    ]
